import{h as t,Fragment as s}from"preact";import{useState as e,useEffect as a}from"preact/hooks";var n=s=>{const e=s.href||"",a=s.disableDefaultStyles||!1,n={...s};return e.startsWith("/")||e.startsWith("#")?n["data-is-internal"]="":(n.target="_blank",n.rel="noopener noreferrer"),n.class=(n.class||"").split(" ").concat([a?"":"styled-link"]).join(" "),n.disableDefaultStyles=null,t("a",{...n})};const l=t=>t.replace(/\s/g,"-").toLowerCase(),r=(t,s)=>"mdx"===s?t.replace(/\[([^\]]+)\]\(([^()]+)\)/g,"$1"):"jsx"===s?"string"==typeof t?t:Array.isArray(t)?t.map((t=>r(t,"jsx"))).join(""):r(t.props.children,"jsx"):void 0;const o=e=>function(a,{slug:o}){const i=r(a.children,"jsx"),c=l(i),u={id:c,children:t(s,null,t(n,{disableDefaultStyles:!0,href:`/post/${o}#${c}`,class:"hashtag"},"#"),t("span",null,a.children)),class:"linkable-head"};return"h2"===e?t("h2",{...u}):"h3"===e?t("h3",{...u}):void 0};o("h2"),o("h3");function i({tags:s}){return t("div",{class:"tags-container"},s.map((s=>t("span",{key:s,class:"tag"},s))))}function c(s){return t("div",{class:"post-card show","data-slug":s.meta.slug},t("span",{class:"post-released-date"},s.meta.dateCreated),t(n,{disableDefaultStyles:!0,href:`/post/${s.meta.slug}`},t("h3",{class:"title"},s.meta.title)),t("p",{class:"description"},s.meta.description),t(i,{tags:s.meta.tags}))}
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */var u;u={red:91,yellow:93,cyan:96},Object.fromEntries(Object.entries(u).map((function(t){return[t[0],"["+t[1]+"m"]})));let d=null;function p(n){const[l,r]=e(n.posts);a((()=>{const t=document.getElementById("posts-search");t.disabled=!1,t.addEventListener("click",o,{once:!0})}),[]);const o=async function(){var t,s,e;d=(await import("/search-logic.js")).filterPosts,this.addEventListener("input",(t=t=>{const s=t.target.value;pa.track({name:"Search Posts",unit:s}),r(d(n.posts||[],s))},void 0===s&&(s=300),function(){for(var a=[],n=0;n<arguments.length;n++)a[n]=arguments[n];clearTimeout(e),e=setTimeout((function(){t.apply(null,a)}),s)}))};return t(s,null,t("main",null,t("h1",null,"Posts"),t("div",{class:"search-container"},t("input",{type:"text",placeholder:"Search Posts",id:"posts-search",disabled:!0}),t("noscript",null,"Search can't work without JavaScript.")),t("div",{class:"posts-container"},0==l.length?t(s,null,t("div",null,"No posts matches your search query :(")):l.map((s=>t(c,{meta:s,key:s.slug}))))))}export{p as default};
